### PR TITLE
fix: add check for solana rent exempt balance

### LINKED ISSUE #1336: USDT0: Solana send fails with `InsufficientFundsForRent` when SOL balance is low
When sending USDT0 from Solana back to LN, the OFT `Send` simulation fails with `InsufficientFundsForRent` on `account_index: 0` (fee payer) unless the user holds substantially more SOL than the LayerZero Fee shown in the initial fee estimation. There's no pre-flight check or friendly error — the user just sees a raw simulation dump, rather than it being caught by the regular sufficient-balance checks.

Observed while swapping ~4 USDT0 (SOL) → LN with 0.00173 SOL in the wallet. I copied the following from the logs, but a pop-up with the same contents was shown on the page. 

```index-dWyECpLC.js:2110 Transaction failed Error: Simulation failed: {"InsufficientFundsForRent":{"account_index":0}}
Logs:
Program ComputeBudget111111111111111111111111111111 invoke [1]
Program ComputeBudget111111111111111111111111111111 success
Program Fuww9mfc8ntAwxPUzFia7VJFAdvLppyZwhPJoXySZXf7 invoke [1]
Program log: Instruction: Send
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
Program log: Instruction: TransferChecked
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 6200 of 977939 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
Program 76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6 invoke [2]
Program log: Instruction: Send
Program 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH invoke [3]
Program log: Instruction: Send
Program 6doghB248px58JSSwG4qejQ46kFMW4AMj7vzJnWZHNZn invoke [4]
Program log: Instruction: QuoteExecutor
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP invoke [5]
Program log: Instruction: GetFee
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP consumed 15678 of 852588 compute units
Program return: 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP CrUBAAAAAAAAAAAAAAAAAPGclZ6DAgAAAAAAAAAAAAAAABBjLV7HawUAAAAAAAAAAQCAzp4l3d9TrQEAAAAAAAA=
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP success
Program 6doghB248px58JSSwG4qejQ46kFMW4AMj7vzJnWZHNZn consumed 46700 of 880992 compute units
Program return: 6doghB248px58JSSwG4qejQ46kFMW4AMj7vzJnWZHNZn M1cLAAAAAAA=
Program 6doghB248px58JSSwG4qejQ46kFMW4AMj7vzJnWZHNZn success
Program 11111111111111111111111111111111 invoke [4]
Program 11111111111111111111111111111111 success
Program HtEYV4xB4wvsj5fgTkcfuChYpvGYzgzwvNhgDZQNh7wW invoke [4]
Program log: Instruction: QuoteDvn
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP invoke [5]
Program log: Instruction: GetFee
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP consumed 15679 of 797340 compute units
Program return: 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP 358BAAAAAAAAAAAAAAAAAPGclZ6DAgAAAAAAAAAAAAAAABBjLV7HawUAAAAAAAAAAQCAzp4l3d9TrQEAAAAAAAA=
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP success
Program HtEYV4xB4wvsj5fgTkcfuChYpvGYzgzwvNhgDZQNh7wW consumed 46859 of 826805 compute units
Program return: HtEYV4xB4wvsj5fgTkcfuChYpvGYzgzwvNhgDZQNh7wW C/MBAAAAAAA=
Program HtEYV4xB4wvsj5fgTkcfuChYpvGYzgzwvNhgDZQNh7wW success
Program 3T7waVnx1W54ZA7XuRmXngoua4hEkRXciNL8stBJAUR4 invoke [4]
Program log: Instruction: QuoteDvn
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP invoke [5]
Program log: Instruction: GetFee
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP consumed 15679 of 761856 compute units
Program return: 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP Xp0BAAAAAAAAAAAAAAAAAPGclZ6DAgAAAAAAAAAAAAAAABBjLV7HawUAAAAAAAAAAQCAzp4l3d9TrQEAAAAAAAA=
Program 8ahPGPjEbpgGaZx2NV1iG5Shj7TDwvsjkEDcGWjt94TP success
Program 3T7waVnx1W54ZA7XuRmXngoua4hEkRXciNL8stBJAUR4 consumed 30958 of 775420 compute units
Program return: 3T7waVnx1W54ZA7XuRmXngoua4hEkRXciNL8stBJAUR4 CvABAAAAAAA=
Program 3T7waVnx1W54ZA7XuRmXngoua4hEkRXciNL8stBJAUR4 success
Program 11111111111111111111111111111111 invoke [4]
Program 11111111111111111111111111111111 success
Program 11111111111111111111111111111111 invoke [4]
Program 11111111111111111111111111111111 success
Program 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH invoke [4]
Program 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH consumed 6628 of 736832 compute units
Program 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH success
Program 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH consumed 180877 of 909343 compute units
Program return: 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH SDoPAAAAAAAAAAAAAAAAAJsAAAABAAAAAAAABTEAAHXY/DXH2FCndZE3Z8Ly4I5gbxFjVHPukQDdocToGqNdiakAAHWeAAAAAAAAAAAAAAAAd2UtWroIYTe1lYdSY/wgAYKRm5JRK9AOfJl2UnTwx0IS3imAHz5Ho7DcT7zEqYnJoHeLGQACAAAAAAAAAAAAAAAARMST215WDhIO0PR9mse5evy5/7MAAAAAADnszw==
Program 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH success
Program 76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6 invoke [3]
Program 76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6 consumed 2127 of 723488 compute units
Program 76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6 success
Program 76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6 consumed 229009 of 948768 compute units
Program return: 76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6 USvQDnyZdlJ08MdCEt4pgB8+R6Ow3E+8xKmJyaB3ixkxBQAAAAAAAEg6DwAAAAAAAAAAAAAAAAA=
Program 76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6 success
Program Fuww9mfc8ntAwxPUzFia7VJFAdvLppyZwhPJoXySZXf7 invoke [2]
Program Fuww9mfc8ntAwxPUzFia7VJFAdvLppyZwhPJoXySZXf7 consumed 2141 of 716192 compute units
Program Fuww9mfc8ntAwxPUzFia7VJFAdvLppyZwhPJoXySZXf7 success
Program Fuww9mfc8ntAwxPUzFia7VJFAdvLppyZwhPJoXySZXf7 consumed 288901 of 999850 compute units
Program return: Fuww9mfc8ntAwxPUzFia7VJFAdvLppyZwhPJoXySZXf7 USvQDnyZdlJ08MdCEt4pgB8+R6Ow3E+8xKmJyaB3ixkxBQAAAAAAAEg6DwAAAAAAAAAAAAAAAABC8TkAAAAAAM/sOQAAAAAA
Program Fuww9mfc8ntAwxPUzFia7VJFAdvLppyZwhPJoXySZXf7 success
    at UP (index-dWyECpLC.js:2114:3041)
    at async Object.send (index-dWyECpLC.js:2114:4070)
    at async j (index-dWyECpLC.js:2114:200934)
    at async N (index-dWyECpLC.js:2114:201947)
    at async Object.onClick (index-dWyECpLC.js:2114:203425)
    at async i.$$click (index-dWyECpLC.js:2114:178209)```

### PR DESCRIPTION
**Pull request by jackstar12**
Closes https://github.com/BoltzExchange/boltz-web-app/issues/1336

There's a minimum required balance for the account to interact with the
token programs, which as of now, is higher than the oft native fee,
which allowed an edge case where our balance check passes but the
transaction still fails.

Also update the rent exempt amount to be fetched from the mainnet rpc
since rent policy can change in the future

## Summary by CodeRabbit

* **Bug Fixes**
  * More accurate native balance checks for Solana OFT sends to prevent failed transactions due to rent-exempt requirements.

* **Performance**
  * Cached Solana rent-exempt balance lookups to reduce RPC calls and speed transaction preparation.

* **Tests**
  * Expanded unit and integration tests around balance calculations and caching.

* **Stability**
  * Improved end-to-end rescue file download/upload handling and UI synchronization for more reliable flows.

### CODE REVIEW

File: src/utils/oft/oft.ts [hunk 1]
```diff
@@ -430,6 +432,19 @@ const getLegacyMeshSourceAmount = (destinationAmount: bigint): bigint => {
...
+    sourceAsset: string,
+    nativeFee: bigint,
+): Promise<bigint> => {
+    const bufferedFee = getBufferedOftNativeFee(nativeFee);
+    const rentExemptMinimum = await getSolanaRentExemptMinimumBalance(
+        sourceAsset,
+        solanaTokenAccountSize,
+    );
+
+    return bufferedFee > rentExemptMinimum ? bufferedFee : rentExemptMinimum;
```
Comment (michael1011) [inline src/utils/oft/oft.ts:445]: Why is it the bigger of these two values? Don't you have to leave the rent exempt amount in the account?

**Review by michael1011 — CHANGES_REQUESTED** [review]

File: src/utils/oft/oft.ts (hunk 1 above)
Comment (jackstar12) [reply src/utils/oft/oft.ts:445]: No. You just need to have more than that at the time of executing the tx, even if it dips below that threshold once done, hence the approach of the max value here.

**Review by michael1011 — APPROVED** [review]
