### PR TITLE
fix: translate create button label on change

### LINKED ISSUE #363: Create button localization doesn't change if I switch language in an min/max amount error state
If swap box shows a min/max amount error because I entered an amount out of bounds and then I go change the language, the swap button language is not changed. For other errors like "Connect Metamask" this didn't happen but didn't test all possible errors.

[Screencast from 12-13-2023 10:17:15 PM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/c81c496b-a85c-42c2-aeb0-34047e711be2)

### PR DESCRIPTION
**Pull request by dni**
closes #363

### CODE REVIEW

File: src/components/CreateButton.tsx [hunk 1]
```diff
@@ -211,13 +215,32 @@ export const CreateButton = () => {
...
+                amount: formatAmount(maximum()),
+                denomination: denomination(),
+            };
+        } else if (buttonLabel() === "invalid_invoice") {
+            return {
+                asset: asset(),
+            };
+        }
+        return {};
+    };
```
Comment (michael1011) [inline src/components/CreateButton.tsx:235]: Do not do this here. Label and arguments should be set together

**Review by michael1011 — CHANGES_REQUESTED** [review]

**Review by kilrau — CHANGES_REQUESTED** [review]
Still found some cases like this one where language is not switched:
image

**Review by kilrau — APPROVED** [review]
