### PR TITLE
fix: block 0 amount receive

### LINKED ISSUE #1333: Strictly block swap creation if receive amount 0 or quote still loading
Currently one can create USDT swaps with a `receiveAmount` of `0` and/or quote still loading:

Image

Leading to a very annoying state:

Image

Which we currently only allow to refund after swap timeout.

### PR DESCRIPTION
**Pull request by jackstar12**
closes: https://github.com/BoltzExchange/boltz-web-app/issues/1333

## Release Notes

* **Bug Fixes**
  * Added validation to prevent swap creation when a send amount is entered but the quoted receive amount is zero, with a clear error message prompting users to increase the send amount.

* **Localization**
  * Added translated error message across all supported languages.

### CODE REVIEW

**Review by kiocos — COMMENTED** [review]
This error message is fine to me, gotta update the english string to match it 

Also remove the end "." in all languages

Image

File: src/i18n/i18n.ts [hunk 1]
```diff
@@ -705,6 +706,8 @@ const dict = {
         retry: "Erneut versuchen",
         error_no_quote:
             "Ein Angebot konnte nicht abgerufen werden. Bitte prüfe deine Verbindung und versuche es erneut.",
+        error_zero_quote:
+            "Der angezeigte Empfangsbetrag ist null. Bitte erhöhe den Sendebetrag und versuche es erneut.",
```
Comment (michael1011) [inline src/i18n/i18n.ts]:
```suggestion
            "Der angezeigte Empfangsbetrag ist Null. Bitte erhöhe den Sendebetrag und versuche es erneut.",
```

File: src/i18n/i18n.ts [hunk 2]
```diff
@@ -211,6 +211,7 @@ const dict = {
         retry: "Retry",
         error_no_quote:
             "A quote could not be obtained. Please check your connection and try again.",
+        error_zero_quote: "Increase send amount",
```
Comment (michael1011) [inline src/i18n/i18n.ts:214]: As Caio said, that's inconsistent

**Review by michael1011 — CHANGES_REQUESTED** [review]

File: src/i18n/i18n.ts (hunk 2 above)
Comment (jackstar12) [reply src/i18n/i18n.ts:214]: Translation fuckup

**Review by michael1011 — APPROVED** [review]
