### PR TITLE
fix: spammy WalletConnect logs

### LINKED ISSUE #1337: WalletConnect logs are spammy
Logs on all my browsers and all my devices contain these which sometimes makes the logs barely readable:
```
    "2026-04-14T09:20:04.345Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:20:14.346Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:20:24.345Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:20:34.346Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:20:44.345Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:20:54.345Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:20:56.767Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:21:04.545Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:21:14.546Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:21:24.345Z WalletConnect event: INITIALIZE",
    "2026-04-14T09:21:34.345Z WalletConnect event: INITIALIZE",
```
and
```
    "2026-04-13T10:45:45.973Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:45:55.973Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:46:05.972Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:46:15.972Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:46:25.973Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:46:35.972Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:46:48.612Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:46:48.970Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:46:55.249Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:47:05.058Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:47:15.058Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:47:25.058Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:47:35.058Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:47:45.058Z WalletConnect event: CONNECT_SUCCESS",
    "2026-04-13T10:47:55.059Z WalletConnect event: CONNECT_SUCCESS",
```

### PR DESCRIPTION
**Pull request by kiocos**
Closes #1337 

## Summary by CodeRabbit

* **Bug Fixes**
  * Reduced duplicate debug messages during wallet connection flows to make connection logs clearer without changing user-visible connection behavior.

* **Refactor**
  * Internal cleanup related to wallet connection logging; no change to public interfaces or end-user functionality.

### CODE REVIEW

File: src/components/WalletConnect.tsx [hunk 1]
```diff
@@ -90,13 +90,13 @@ export const WalletConnect = () => {
...
         created.subscribeEvents((ev) => {
-            log.debug(`WalletConnect event: ${ev.data.event}`);
-
             if (ev.data.event !== "MODAL_CLOSE") {
                 setOpenWalletConnectModal(false);
                 return;
             }
 
+            log.debug(`WalletConnect event: ${ev.data.event}`);
+
```
Comment (michael1011) [inline src/components/WalletConnect.tsx]: THis will only ever log `MODAL_CLOSE`

**Review by michael1011 — CHANGES_REQUESTED** [review]
The actualy question is *why* those logs are so spammy. Not just removing the log line

**Comment by kiocos** [comment]
> The actualy question is _why_ those logs are so spammy. Not just removing the log line

Reown's state subscription flushes events every 10 seconds:
```
setInterval(() => {
    EventsController._submitPendingEvents();
}, FLUSH_EVENTS_INTERVAL_MS);

```
I haven't installed the old version yet, but I believe it only started happening after we [upgraded to reown 1.8.19](https://github.com/BoltzExchange/boltz-web-app/commit/ceff4ad#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519). Before that, their state management was simpler and didn't have the "flush every 10 sec" we see now (and our spammed logs appear every 10 sec). I didn't see any other change on our side that could have caused it.

Anyhow, just pushed again. I tested the behavior before and it looked alright, but I might had some cache. Tested again now, looks correct.

**Review by michael1011 — APPROVED** [review]
