### PR TITLE
fix: Tron mobile wallet detection

### LINKED ISSUE #1386: Use mnemonic backup for Tron sends on mobile
Just like [EVM sends on mobile](https://github.com/BoltzExchange/boltz-web-app/blob/b2600d6de7800a667bffc6cd20f654593f982b9b/src/components/BackupDownloadContent.tsx#L19), Tron sends on mobile would need to use mnemonic-based backup as Tron Mobile wallets like TronLink do not allow downloading backup files.

Follow-up of https://github.com/BoltzExchange/boltz-web-app/pull/1354.

### PR DESCRIPTION
**Pull request by michael1011**
Closes https://github.com/BoltzExchange/boltz-web-app/issues/1386

## Summary by CodeRabbit

* **Improvements**
  * Enhanced detection of available wallet types (EVM and TRON) on mobile browsers
  * Updated backup recovery and wallet connection flows to accurately reflect which wallets are accessible to users

### CODE REVIEW

**Comment by michael1011** [comment]
@coderabbitai review

File: src/context/Web3.tsx [hunk 1]
```diff
@@ -71,6 +71,9 @@ declare global {
     interface Window {
         // @ts-expect-error - conflicts with @reown/appkit-utils non-optional declaration
         ethereum?: EIP1193Provider;
+        tron?: unknown;
+        tronLink?: unknown;
+        tronWeb?: unknown;
```
Comment (jackstar12) [inline src/context/Web3.tsx:76]: So the tron devs couldn't agree on a name here?

Comment (michael1011) [reply src/context/Web3.tsx:76]: These are all slightly different versions of the same thing. All we care about is checking if its a custom mobile browser for which any of those not being undefined is good enough of a heuristic

**Review by jackstar12 — APPROVED** [review]
