### PR TITLE
fix: revalidate amount on backspace deletion

### LINKED ISSUE #718: Deleting amount with backspace doesn't trigger revalidation
If I first enter a valid address, then any amount (can be invalid)
image

And then delete the amount with backspace, web app should detect this and switch back to
image

Instead it has "Create Atomic Swap" button active and then returns this API error:
image

### PR DESCRIPTION
**Pull request by gabriel-cmps**
Closes #718.

### CODE REVIEW

File: src/pages/Create.tsx [hunk 1]
```diff
@@ -82,11 +82,14 @@ const Create = () => {
...
-            setSendAmount(BigNumber(0));
-        }
+    const shouldResetOnEmptyAmount = (amount: string): boolean => {
+        const isEmpty = amount === "";
+        if (!isEmpty) return false;
+
+        setReceiveAmount(BigNumber(0));
+        setSendAmount(BigNumber(0));
+        validateAmount();
+        return true;
```
Comment (kiocosta) [inline src/pages/Create.tsx:92]: IMO this needs more separation of concerns.

`setReceiveAmount`, `setSendAmount` and `validateAmount` could be separated into a single function and we could have a different function just for the boolean part.

File: src/pages/Create.tsx [hunk 2]
```diff
@@ -95,7 +98,7 @@ const Create = () => {
             .trim()
             .replaceAll(" ", "")
             .replaceAll(",", ".");
-        checkEmptyAmount(amount);
+        if (shouldResetOnEmptyAmount(amount)) return;
```
Comment (kiocosta) [inline src/pages/Create.tsx:101]: After breaking the aforementioned function into 2, perhaps it could make sense to divide this into more lines?
This is just my opinion, but I think having the `{ }` makes life a bit easier when debugging.

**Review by kiocosta — APPROVED** [review]

File: src/pages/Create.tsx (hunk 1 above)
Comment (gabriel-cmps) [reply src/pages/Create.tsx:92]: I agree, I'll do that.

File: src/pages/Create.tsx (hunk 2 above)
Comment (gabriel-cmps) [reply src/pages/Create.tsx:101]: I hadn't thought of it that way, it actually seems better. I'll make that change.

**Review by kiocosta — APPROVED** [review]
Tested ACK.

**Review by michael1011 — APPROVED** [review]
