### PR TITLE
fix: Don't show swaps as 'refundable' when there was no lockup tx

### LINKED ISSUE #806: Don't show swaps as "refundable" in /refund when there was no lockup tx
As a side effect of us (as of [recently](https://github.com/BoltzExchange/boltz-backend/pull/762)) setting swaps with expired invoices to status `invoice.failedToPay`, these are now all showing as "Refundable" in our refund page. Previously status `invoice.failedToPay` would only apply if there were funds locked up, we actually tried to pay the invoice and that failed.
Image

Now, status `invoice.failedToPay` also applies to swaps with expired invoices, no matter if there ever were funds locked up or not. Swaps that don't have a lockup tx/funds locked (swap was created by money never moved) should NOT show here as "refundable":
Image

Consequently, WebApp should query swap endpoints to see if there is a lockup tx each and only show the ones that *do* have a lockup tx:
https://api.boltz.exchange/swagger#/Submarine/get_swap_submarine__id__transaction
https://api.boltz.exchange/swagger#/Chain%20Swap/get_swap_chain__id__transactions

### PR DESCRIPTION
**Pull request by kiocosta**
Closes #806

I have tested this by creating a few swaps and:
- letting them expire without paying (these were not displayed);
- paying them after they've expired (these were displayed);
- paying an incorrect amount (these were displayed);

### CODE REVIEW

**Review by kilrau — APPROVED** [review]
Sorry for the late review, many of us are travelling. tACK from my side (no code review)

I tested the following 4 scenarios:
1. paying correctly and letting a swap fail (e.g.`invoice.failedToPay`): displayed ✅
2. paying an incorrect amount: displayed ✅
3. letting a swap expire without paying: not displayed ✅
4. With "paying them after they've expired (these were displayed);" you made it sound like you are already did https://github.com/BoltzExchange/boltz-web-app/issues/809 but that's not the case. All good, let's handle #809 separately. ✅

File: src/pages/Refund.tsx [hunk 1]
```diff
@@ -27,17 +27,18 @@ const Refund = () => {
...
+        const swapsToRefund = allSwaps
             .filter(refundSwapsSanityFilter)
             .filter((swap) =>
-                [
-                    swapStatusFailed.InvoiceFailedToPay,
-                    swapStatusFailed.TransactionLockupFailed,
-                ].includes(swap.status),
+                [swapStatusFailed.TransactionLockupFailed].includes(
+                    swap.status,
+                ),
```
Comment (michael1011) [inline src/pages/Refund.tsx:37]:
```suggestion
                swapStatusFailed.TransactionLockupFailed === swap.status,
```

**Review by michael1011 — CHANGES_REQUESTED** [review]

File: src/pages/Refund.tsx (hunk 1 above)
Comment (kiocosta) [reply src/pages/Refund.tsx]: @michael1011 done!
