### PR TITLE
fix: urlParam `receiveAsset` not working

### LINKED ISSUE #884: URL Params: setting `receiveAsset` doesn't work anymore
`receiveAsset` is ignored, test e.g. with https://boltz.exchange/?sendAsset=BTC&receiveAsset=RBTC . Likely that https://github.com/BoltzExchange/boltz-web-app/blob/main/src%2Fcontext%2FCreate.tsx#L100-L101 bricked it. Let's fix it and add tests for all URL params.

### PR DESCRIPTION
**Pull request by kiocosta**
Closes #884

The problem occurred when`setDestination` returned `destinationAsset` as `null`, but the `if` checked if `destinationAsset` was `undefined`.
https://github.com/BoltzExchange/boltz-web-app/blob/cb62f517c97cf35e798922b79feaa8900cd88f16/src/context/Create.tsx#L88-L100

Fixed by returning `destinationAsset` as `undefined` (instead of redefining it as `null`) and added unit tests covering this scenario.

### CODE REVIEW

**Review by kilrau — APPROVED** [review]
tACK

File: src/context/Create.tsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ const setDestination = (
     setAssetReceive: Setter<string>,
     setInvoice: Setter<string>,
     setOnchainAddress: Setter<string>,
-): { destinationAsset: string | null; destination: string | null } => {
+): { destinationAsset: string; destination: string } => {
```
Comment (michael1011) [inline src/context/Create.tsx:26]:
```suggestion
): { destinationAsset?: string; destination?: string } => {
```

**Review by michael1011 — CHANGES_REQUESTED** [review]
Works but needs the correct return type

File: src/context/Create.tsx (hunk 1 above)
Comment (kiocosta) [reply src/context/Create.tsx]: @michael1011 fixed :)

**Review by michael1011 — APPROVED** [review]
