### PR TITLE
fix: Settings icon overlap on very small screens

### LINKED ISSUE #720: UI: Settings wheel overlay on very small screens
image

### PR DESCRIPTION
**Pull request by kiocosta**
Closes #720  

### Before
image

### Now
image

### CODE REVIEW

File: src/pages/Pay.tsx [hunk 1]
```diff
@@ -139,17 +139,19 @@ const Pay = () => {
...
     return (
-        <div data-status={status()} class="frame">
-            <SettingsCog />
-            <h2>
-                {t("pay_invoice", { id: params.id })}
-                <Show when={swap()}>
-                    <SwapIcons swap={swap()} />
-                </Show>
-            </h2>
+        <div data-status={status()} class="frame" id="pay">
```
Comment (michael1011) [inline src/pages/Pay.tsx:142]:
```suggestion
        <div data-status={status()} class="frame">
```
Not being used as far as I can tell

**Review by michael1011 — CHANGES_REQUESTED** [review]
Looks good on mobile

One minor comment; can be merged after

File: src/pages/Pay.tsx (hunk 1 above)
Comment (kiocosta) [reply src/pages/Pay.tsx]: @michael1011 leftover from a previous attempt, removed!
